version: 1.0.{build}

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module Pester -MinimumVersion 3.4.6 -Scope CurrentUser -Force | Out-Null

build_script:
- ps: Invoke-Pester -OutputFile Result.xml -OutputFormat NUnitXml
- ps: type .\Result.xml
