version: 1.0.{build}

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force | Out-Null

build_script:
- ps: |
    Import-Module Pester
    (get-module pester).version.ToString()
    Invoke-Pester -OutputFile Result.xml -OutputFormat NUnitXml
    type .\Result.xml
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Result.xml))
